language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script: 
  - npm run build
  - npm run coveralls-test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage